"use client";
import { useState } from "react";
import { Play,Pause,Users,Film,Radio,Link2,Volume2,VolumeX,Maximize,HelpCircle,ShieldCheck,Copy,Check,Loader2,LogOut } from "lucide-react";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { useRoom } from "@/hooks/use-room";
const fmt=(n:number)=>`${Math.floor((n||0)/60)}:${Math.floor((n||0)%60).toString().padStart(2,"0")}`;
function DriveIcon(){return <svg width="22" height="22" viewBox="0 0 24 22" aria-hidden="true"><path fill="#34a853" d="M8 1h8l-8 14H0z"/><path fill="#fbbc04" d="m16 1 8 14h-8L8 1z"/><path fill="#4285f4" d="M0 15h24l-4 7H4z"/></svg>;}
export default function Home(){
 const s=useRoom();const {room}=s;
 const [help,setHelp]=useState(false),[invite,setInvite]=useState(false),[copied,setCopied]=useState(false);
 async function copy(){try{await navigator.clipboard.writeText(s.roomUrl);setCopied(true);toast.success("Invitation link copied");setTimeout(()=>setCopied(false),2000);}catch{setInvite(true);}}
 function join(){s.setError("");s.setJoinOpen(true);}
 return <div className="app-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="Watch2Gether home"><span className="brand-mark"><Play size={19} fill="currentColor"/></span>watch<span>2</span>gether</a><div className="header-actions"><button className="quiet" onClick={()=>setHelp(true)}><HelpCircle size={17}/><span>How it works</span></button>{room?<button className="outline" onClick={()=>void s.leave()}><LogOut size={16}/>Leave room</button>:<button className="outline" onClick={join}><Users size={17}/>Join a room</button>}</div></header>
 <main><div className="page-heading"><div><div className="eyebrow">THE GOOD PART IS WATCHING TOGETHER</div><h1>{room?room.title:"Your next movie night starts here."}</h1><p>{room?`Hosted by ${room.hostName}. Get comfortable, you’re in good company.`:"One video. One room. Everyone in the moment."}</p></div><div className="drive-badge"><DriveIcon/>Made for Google Drive</div></div>
 <div className={`watch-layout ${room?"in-room":""}`}><section className="watch-column" aria-label="Video player">
 <div className={`player ${room?"has-video":""}`} ref={s.player}>
 <div className="player-top"><span title={room?.videoName}><Film size={15}/>{room?room.videoName:"YOUR SHARED SCREEN"}</span><span className="player-chip" aria-live="polite">{room?(s.connected?"Connected":"Reconnecting…"):"Ready when you are"}</span></div>
 {room?<><video ref={s.video} src={`/api/rooms/${room.id}/stream?member=${encodeURIComponent(s.memberToken)}`} preload="metadata" playsInline muted={s.muted} onLoadedMetadata={()=>{s.setDuration(s.video.current?.duration||0);s.setReady(true);}} onTimeUpdate={()=>{if(!s.scrubbing.current)s.setCurrent(s.video.current?.currentTime||0);}} onEnded={()=>{if(s.isHost)void s.control(false,s.video.current?.duration||0);}} onError={()=>s.setMediaError("This video couldn’t be played. Check its Drive sharing settings, download permissions, and browser-compatible format (MP4 recommended).")}/>
 {!s.ready&&!s.mediaError&&<div className="video-overlay"><Loader2 className="spin" size={30}/><p>Loading your Drive video…</p></div>}
 {s.mediaError&&<div className="video-overlay"><Film size={38}/><p className="media-error" role="alert">{s.mediaError}</p><button className="outline" onClick={()=>{s.setMediaError("");s.video.current?.load();}}>Try again</button></div>}
 {s.needsTap&&!s.mediaError&&<button className="autoplay-button" onClick={()=>void s.video.current?.play().then(()=>s.setNeedsTap(false)).catch(()=>toast.error("Playback couldn’t start. Try again."))}><Play fill="currentColor"/>Tap to join playback</button>}
 </>:<div className="player-empty"><div className="empty-play"><Play size={32} fill="currentColor"/></div><h2>A seat for everyone.</h2><p>Bring a video from your Drive.<br/>We’ll bring everyone together.</p><div className="empty-tag"><Users size={15}/>Different places. Same playhead.</div></div>}
 <div className="player-controls"><Slider aria-label="Video position" min={0} max={s.duration||100} step={.1} value={[s.current]} disabled={!room||!s.isHost||!s.ready||!s.connected} onValueChange={v=>{s.scrubbing.current=true;s.setCurrent(v[0]);}} onValueCommit={v=>{s.scrubbing.current=false;if(s.video.current)s.video.current.currentTime=v[0];void s.control(room?.playing||false,v[0]);}}/><div className="control-row"><div>
 <button aria-label={room?.playing?"Pause for everyone":"Play for everyone"} disabled={!room||!s.isHost||!s.ready||!s.connected} onClick={()=>void s.control(!room?.playing)}>{room?.playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}</button>
 <button aria-label={s.muted?"Unmute":"Mute"} disabled={!room} onClick={()=>s.setMuted(!s.muted)}>{s.muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><span className="time">{fmt(s.current)} <span>/ {fmt(s.duration)}</span></span></div>
 <div><span className="sync-label"><Radio size={14}/>{room?(s.isHost?"You control playback":"Following the host"):"Synced playback"}</span><button aria-label="Fullscreen" onClick={()=>void s.player.current?.requestFullscreen().catch(()=>toast.error("Fullscreen isn’t available in this browser."))}><Maximize size={18}/></button></div></div></div></div>
 <div className="below-player"><div className="mini-icon"><Radio size={20}/></div><div><h3>{room?"Stay in the same moment":"No more “3, 2, 1… play.”"}</h3><p>{room?"The host’s play, pause, and seek changes are shared with everyone.":"Play, pause, or skip. Your room stays together automatically."}</p></div><span className="small-label">{room?"HOST CONTROLLED":"ALL IN SYNC"}</span></div></section>
 <aside className="room-panel">{!room?<><div className="panel-heading"><span className="panel-icon"><Users size={22}/></span><h2>Make room for your people.</h2><p>A movie night is just a link away.</p></div>
 <form className="setup-form" onSubmit={e=>{e.preventDefault();void s.createRoom().catch(()=>{});}}>
 <label>Your name<input value={s.name} onChange={e=>s.setName(e.target.value)} placeholder="What should we call you?" required maxLength={32} autoComplete="nickname"/></label>
 <label>Room name <span className="optional">optional</span><input value={s.title} onChange={e=>s.setTitle(e.target.value)} placeholder="Friday movie night" maxLength={60}/></label>
 <label>Google Drive video link<div className="input-icon"><Link2 size={17}/><input value={s.driveLink} onChange={e=>s.setDriveLink(e.target.value)} placeholder="Paste your video link" required type="url"/></div></label>
 <p className="field-note"><ShieldCheck size={15}/>Set the video’s access to “Anyone with the link” in Google Drive.</p>{s.error&&<p className="error" role="alert">{s.error}</p>}
 <button className="primary full" disabled={s.busy}>{s.busy?<Loader2 className="spin" size={18}/>:<Play size={17} fill="currentColor"/>}{s.busy?"Preparing your room…":"Create a room"}</button></form>
 <div className="join-divider"><span>Already have an invite?</span><button onClick={join}>Join a room</button></div></>:
 <><div className="panel-heading"><span className="panel-icon"><Users size={22}/></span><h2>Your viewing room</h2><p>{room.members.length} {room.members.length===1?"person":"people"} here · {s.connected?"Connected":"Reconnecting"}</p></div>
 <button className="primary full" onClick={()=>void copy()}>{copied?<Check size={18}/>:<Copy size={18}/>} {copied?"Link copied":"Invite your people"}</button><p className="invite-note">Anyone with your invitation link can join.</p>
 <div className="people-list"><h3>IN THE ROOM</h3>{room.members.map((m,i)=><div className="person" key={`${m.name}-${i}`}><span className={`avatar color-${i%3}`}>{m.name.slice(0,1).toUpperCase()}</span><span>{m.name}</span>{m.isHost&&<span className="host-badge">Host</span>}</div>)}</div>
 <div className="room-note"><ShieldCheck size={18}/><p>The host controls the shared screen. Your volume is always yours.</p></div><button className="quiet full" onClick={()=>setInvite(true)}><Link2 size={16}/>View room link</button></>}</aside></div>
 {!room&&<section className="steps" aria-label="How to watch together">{[["01","Bring your video","Paste a shared Google Drive link."],["02","Bring your people","Send them your room’s invite link."],["03","Press play, together","Settle in. We’ll keep you in sync."]].map(step=><div key={step[0]}><span className="step-number">{step[0]}</span><div><h3>{step[1]}</h3><p>{step[2]}</p></div></div>)}</section>}
 </main><footer><span>Good films. Better company.</span><span>watch2gether · Made for shared moments</span></footer>
 <Dialog open={s.joinOpen} onOpenChange={v=>{s.setJoinOpen(v);s.setError("");}}><DialogContent className="w2g-dialog"><DialogTitle>There’s a seat for you.</DialogTitle><DialogDescription>Enter your name and the invitation link to join the room.</DialogDescription><form className="setup-form" onSubmit={e=>{e.preventDefault();void s.joinRoom();}}><label>Your name<input value={s.name} onChange={e=>s.setName(e.target.value)} required maxLength={32} placeholder="Your name"/></label><label>Room invitation<input value={s.joinLink} onChange={e=>s.setJoinLink(e.target.value)} required placeholder="Paste a room link"/></label>{s.error&&<p className="error" role="alert">{s.error}</p>}<button className="primary full" disabled={s.busy}>{s.busy?<Loader2 className="spin" size={17}/>:<Users size={17}/>} {s.busy?"Joining…":"Join the room"}</button></form></DialogContent></Dialog>
 <Dialog open={invite} onOpenChange={setInvite}><DialogContent className="w2g-dialog"><DialogTitle>Save a seat for your friends.</DialogTitle><DialogDescription>Share this link. Your friends can join without an account.</DialogDescription><input aria-label="Room invitation link" value={s.roomUrl} readOnly onFocus={e=>e.target.select()}/><button className="primary" onClick={()=>void copy()}><Copy size={17}/>Copy invitation</button></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="w2g-dialog"><DialogTitle>A movie night in three steps.</DialogTitle><DialogDescription>Watch a shared Google Drive video with anyone you invite.</DialogDescription><ol className="help-list"><li>In Google Drive, open your video’s Share settings and select <strong>Anyone with the link</strong>. Make sure viewers can download it.</li><li>Paste its link here, enter your name, and create a room.</li><li>Copy the room invitation and send it to your friends. The host controls play, pause, and seeking.</li></ol><p className="field-note">MP4 with H.264 video and AAC audio works best. Drive quotas or download restrictions may prevent playback. Rooms expire after 24 hours.</p></DialogContent></Dialog><Toaster theme="dark"/></div>;
}

