import { env } from "cloudflare:workers";
import { AppError } from "./drive";
export type RoomRow={id:string;title:string;host_name:string;host_hash:string;drive_id:string;resource_key:string|null;video_name:string;playing:number;position:number;updated_at:number;version:number;expires_at:number};
export function database(){if(!env.DB)throw new AppError("Rooms are temporarily unavailable. Please try again shortly.",503);return env.DB;}
export const token=()=>crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");
export async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(v=>v.toString(16).padStart(2,"0")).join("");}
export function cleanName(value:unknown){if(typeof value!=="string" || !value.trim() || value.length>32)throw new AppError("Enter your name (up to 32 characters).");return value.trim();}
export function sameOrigin(request:Request){const origin=request.headers.get("origin");if(origin && origin!==new URL(request.url).origin)throw new AppError("This request must come from your viewing room.",403);}
export async function payload(request:Request){sameOrigin(request);if(Number(request.headers.get("content-length")||0)>4096)throw new AppError("The request is too large.",413);try{return await request.json() as Record<string,unknown>;}catch{throw new AppError("Invalid request.");}}
export async function findRoom(id:string){if(!/^[a-zA-Z0-9_-]{16,64}$/.test(id))throw new AppError("This room link is invalid.",404);const room=await database().prepare("SELECT * FROM rooms WHERE id = ? AND expires_at > ?").bind(id,Date.now()).first<RoomRow>();if(!room)throw new AppError("This room doesn’t exist or has expired. Ask your host for a new invitation.",404);return room;}
export async function requireMember(request:Request,room:RoomRow,query=false){const raw=query?new URL(request.url).searchParams.get("member"):request.headers.get("x-member-token");if(!raw||raw.length>128)throw new AppError("Join this room to watch the video.",401);const member=await database().prepare("SELECT * FROM members WHERE room_id = ? AND token_hash = ?").bind(room.id,await hash(raw)).first<{token_hash:string;name:string;is_host:number;last_seen:number}>();if(!member)throw new AppError("Join this room to watch the video.",401);return member;}
export async function view(room:RoomRow){const members=await database().prepare("SELECT name, is_host FROM members WHERE room_id = ? AND last_seen > ? ORDER BY is_host DESC, name ASC LIMIT 50").bind(room.id,Date.now()-45000).all<{name:string;is_host:number}>();return {id:room.id,title:room.title,hostName:room.host_name,driveId:room.drive_id,videoName:room.video_name,playing:!!room.playing,position:room.position,updatedAt:room.updated_at,version:room.version,expiresAt:room.expires_at,serverTime:Date.now(),members:members.results.map(m=>({name:m.name,isHost:!!m.is_host}))};}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store","Referrer-Policy":"no-referrer"}});}
export function failure(error:unknown){if(error instanceof AppError)return json({error:error.message},error.status);console.error("Room operation failed",error instanceof Error?error.message:"Unknown error");return json({error:"The room is temporarily unavailable. Please try again."},503);}
