"use client";
import { useEffect,useRef,useState } from "react";
import { toast } from "sonner";
import type { SubtitleCue } from "@/lib/subtitles";
export type Room={id:string;title:string;videoName:string;playing:boolean;position:number;updatedAt:number;version:number;serverTime:number;hostName:string;expiresAt:number;subtitle:{name:string;revision:number}|null;members:{name:string;isHost:boolean}[]};
type ApiResponse={room:Room;hostToken:string;memberToken:string;isHost:boolean;error?:string};
async function api(path:string,body?:object,headers?:Record<string,string>){const response=await fetch(path,{method:body?"POST":"GET",headers:{"Content-Type":"application/json",...headers},body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await response.json() as ApiResponse;if(!response.ok)throw new Error(data.error||"Something went wrong. Please try again.");return data;}
export function useRoom(){
 const [room,setRoom]=useState<Room|null>(null),[name,setName]=useState(""),[title,setTitle]=useState(""),[driveLink,setDriveLink]=useState("");
 const [joinOpen,setJoinOpen]=useState(false),[joinLink,setJoinLink]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[connected,setConnected]=useState(false);
 const [hostToken,setHostToken]=useState(""),[memberToken,setMemberToken]=useState(""),[current,setCurrent]=useState(0),[duration,setDuration]=useState(0),[muted,setMuted]=useState(false),[ready,setReady]=useState(false),[needsTap,setNeedsTap]=useState(false),[mediaError,setMediaError]=useState("");
 const video=useRef<HTMLVideoElement>(null),player=useRef<HTMLDivElement>(null),latest=useRef<Room|null>(null),clockOffset=useRef(0),updating=useRef(false),scrubbing=useRef(false),controlBusy=useRef(false);
 const isHost=!!hostToken;const roomUrl=room&&typeof window!=="undefined"?`${window.location.origin}/?room=${room.id}`:"";
 function accept(r:Room){if(latest.current?.id===r.id&&latest.current.version>r.version)return;clockOffset.current=r.serverTime-Date.now();latest.current=r;setRoom(r);}
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("room");if(id){setJoinLink(id);setJoinOpen(true);}setName(localStorage.getItem("w2g-name")||"");},[]);
 async function createRoom(input?:{name:string;title?:string;driveLink:string}){
  if(busy)throw new Error("A room is already being prepared.");setBusy(true);setError("");
  try{const values=input||{name,title,driveLink};const data=await api("/api/rooms",values);sessionStorage.setItem(`w2g-host-${data.room.id}`,data.hostToken);sessionStorage.setItem(`w2g-member-${data.room.id}`,data.memberToken);localStorage.setItem("w2g-name",values.name);setName(values.name);setHostToken(data.hostToken);setMemberToken(data.memberToken);accept(data.room);setConnected(true);window.history.replaceState({},"",`/?room=${data.room.id}`);toast.success("Your room is ready. Invite your people.");return {id:data.room.id,invitation:`${window.location.origin}/?room=${data.room.id}`};}
  catch(e){setError((e as Error).message);throw e;}finally{setBusy(false);}
 }
 async function joinRoom(){setBusy(true);setError("");try{let id=joinLink.trim();try{id=new URL(id).searchParams.get("room")||"";}catch{}if(!/^[a-zA-Z0-9_-]{16,64}$/.test(id))throw new Error("Paste a valid room invitation link.");const host=sessionStorage.getItem(`w2g-host-${id}`)||"";const data=await api(`/api/rooms/${id}/join`,{name,memberToken:sessionStorage.getItem(`w2g-member-${id}`),hostToken:host});sessionStorage.setItem(`w2g-member-${id}`,data.memberToken);localStorage.setItem("w2g-name",name);setHostToken(data.isHost?host:"");setMemberToken(data.memberToken);accept(data.room);setConnected(true);setJoinOpen(false);window.history.replaceState({},"",`/?room=${id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!room?.id||!memberToken)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const data=await api(`/api/rooms/${room!.id}`,undefined,{"X-Member-Token":memberToken});if(!cancelled&&!updating.current){accept(data.room);setConnected(true);}}catch{if(!cancelled)setConnected(false);}if(!cancelled)timer=setTimeout(poll,1200);}void poll();return()=>{cancelled=true;clearTimeout(timer);};},[room?.id,memberToken]);
 useEffect(()=>{if(!room||!ready)return;const sync=()=>{const v=video.current,r=latest.current;if(!v||!r||updating.current||scrubbing.current)return;const elapsed=r.playing?Math.max(0,(Date.now()+clockOffset.current-r.updatedAt)/1000):0;const target=Math.min(Number.isFinite(v.duration)?v.duration:Infinity,r.position+elapsed);if(Math.abs(v.currentTime-target)>1.4)v.currentTime=target;if(r.playing&&v.paused&&!v.ended)v.play().then(()=>setNeedsTap(false)).catch(()=>setNeedsTap(true));else if(!r.playing&&!v.paused)v.pause();};sync();const timer=setInterval(sync,700);return()=>clearInterval(timer);},[room,ready]);
 async function control(playing:boolean,position=video.current?.currentTime||0){if(!room||!isHost||!connected||controlBusy.current)return;controlBusy.current=true;updating.current=true;try{const data=await api(`/api/rooms/${room.id}/control`,{playing,position},{"X-Host-Token":hostToken});accept(data.room);}catch(e){toast.error((e as Error).message);}finally{updating.current=false;controlBusy.current=false;}}
 async function saveSubtitles(input:{name:string;cues:SubtitleCue[]}|null){if(!room||!isHost)throw new Error("Only the host can change the room’s subtitles.");const data=await api(`/api/rooms/${room.id}/subtitles`,input?{action:"add",...input}:{action:"remove"},{"X-Host-Token":hostToken});accept(data.room);}
 async function leave(){if(room)try{await api(`/api/rooms/${room.id}/leave`,{},{"X-Member-Token":memberToken});}catch{}latest.current=null;setRoom(null);setHostToken("");setMemberToken("");setReady(false);setMediaError("");setNeedsTap(false);setConnected(false);setCurrent(0);setDuration(0);window.history.replaceState({},"","/");}
 const toolsRef=useRef({createRoom,room});toolsRef.current={createRoom,room};
 useEffect(()=>{type Registry={registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>};const ctx=(document as Document&{modelContext?:Registry}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(ctx.registerTool({name:"create_watch_room",description:"Create a synchronized viewing room from a publicly shared Google Drive video and show it on screen.",inputSchema:{type:"object",properties:{name:{type:"string",minLength:1,maxLength:32},title:{type:"string",maxLength:60},driveLink:{type:"string"}},required:["name","driveLink"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const p=input as Record<string,unknown>;if(!p||typeof p.name!=="string"||!p.name.trim()||p.name.length>32||typeof p.driveLink!=="string"||(p.title!==undefined&&(typeof p.title!=="string"||p.title.length>60)))throw new Error("Provide your name and a valid Drive video link.");if(toolsRef.current.room)throw new Error("Leave the current room before creating another.");return toolsRef.current.createRoom(p as {name:string;title?:string;driveLink:string});}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 return {room,name,setName,title,setTitle,driveLink,setDriveLink,joinOpen,setJoinOpen,joinLink,setJoinLink,busy,error,setError,connected,isHost,current,setCurrent,duration,muted,setMuted,ready,setReady,needsTap,setNeedsTap,mediaError,setMediaError,video,player,scrubbing,roomUrl,memberToken,createRoom,joinRoom,control,leave,setDuration,saveSubtitles};
}
